# Constants for requestNo.
int64 REQUEST_REFUELLING=1
int64 REPORT_TASK_FINISHED=2
int64 REPORT_FINISHED_REFUELLING=3
int64 REPORT_ARRIVAL_TO_DESTINATION=4
int64 REPORT_TAKEOFF_FINISHED=5
int64 REPORT_LAND_COMPLETE=6
int64 REPORT_WAYPOINT_FAILED=7
# Message
int64 UAVID
int64 requestNo
-----
bool success