# Start one of the tasks using the VisualControl node.
int8 SEARCH_WALL=1
int8 PICK_UP_BRICK=2
int8 PLACE_BRICK_ON_WALL=3
int8 PLACE_BRICK_ON_UGV=4
# Start the task.
int8 task
---
# Response when the task completes.  true = successful.
bool success
---
# Feedback. Percentage complete, 0 to 100.  A rough indication that something is happening.
int8 percentage
